### ISSUE TITLE
Base64 Recipe Returning ASCII integer value(s)

### ISSUE THREAD

**Issue by weslambert** [gchq/CyberChef-server#6]
Is there any way to return the output of a base64 op as ASCII text vs integer values?

For example, if I do the following:

`curl -XPOST -H "Content-Type: application/json" http://192.168.1.203:3000/bake -d '{"input":"dGVzdA==", "recipe":{"op":"From Base64"}}'`

I get the following as the response:

`[116,101,115,116]`

How would I modify the request to receive `test` as the response?

**Comment by d98762625** [comment]
You're getting this because the `outputType` of `FromBase64` is `byteArray` - [see here.](https://github.com/gchq/CyberChef/blob/master/src/core/operations/FromBase64.mjs#L26)

There's a card in the project for this repo for work to optionally define the return type you get from a request, which would solve your problem: [card link here](https://github.com/gchq/CyberChef-server/projects/1#card-27013065). Work has not been started on this yet - feel free to contribute if you have a pressing requirement for it!

**Comment by weslambert** [comment]
@d98762625 ,

That certainly makes sense, and thank you for the quick response.  I will take a look at the referenced card and see what I can come up with.

Thanks again!
Wes

**Comment by d98762625** [comment]
No problem. Closing for now.
